### ISSUE TITLE
Add more Python Mini Projects

### ISSUE THREAD

**Issue by sreekeshiyer** [sreekeshiyer/python-beginner-mini-projects#1]
Looking to add more Mini Projects to the Repository. 

Hot topics to explore:
- Usage of Public APIs
- Scripts to automate simple stuff
- Working with services in AWS using clients like `boto3`
- Simple Data Analytics Projects

Please take a look at [Contributing.MD](https://github.com/sreekeshiyer/python-beginner-mini-projects/blob/main/contributing.MD) before contributing. 

Thanks!

**Comment by Kabir1302** [comment]
hey pls assign it to me

**Comment by sreekeshiyer** [comment]
We're quite near the end of hacktoberfest 2022. I'm glad to see so many contributions to this repository. Appreciate every project that we've received this month. Cheers!
