### ISSUE TITLE
A chat bot

### ISSUE THREAD

**Issue by kodepirate** [sreekeshiyer/python-beginner-mini-projects#17]
I like to make a chatbot for hacktoberfest @sreekeshiyer

**Comment by sreekeshiyer** [comment]
Would be a little too advanced for Beginners I'm afraid.

**Comment by kodepirate** [comment]
It will be not that hard, it will be really a good one  ,You can rely on that @sreekeshiyer

**Comment by sreekeshiyer** [comment]
Go ahead then mate, I'll be waiting for your PR.

**Comment by kodepirate** [comment]
Have a look , created the PR @sreekeshiyer

**Comment by kodepirate** [comment]
It's really great to work in this repo, I also working as a mentee in the hacktoberfest, you are doing great @sreekeshiyer

**Comment by kodepirate** [comment]
Will you please add the hacktoberfest accepted  label @sreekeshiyer
